snowflake_stocks:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"
      user: "{{ env_var('USER') }}"
      password: "{{ env_var('PASSWORD') }}"
      role: ACCOUNTADMIN
      database: "{{ env_var('DATABASE') }}"
      warehouse: "{{ env_var('WAREHOUSE') | default('COMPUTE_WH') }}"
      schema: "{{ env_var('SCHEMA') }}"
      threads: 4